spring.application.name=marketplace

# H2 database configuration
spring.datasource.url=jdbc:h2:file:${user.home}/webDevProject/data/23205030DB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# JPA configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# Set session timeout (e.g., 30 minutes)
server.servlet.session.timeout=30m

# Enable Spring Session JDBC to create tables automatically
spring.session.jdbc.initialize-schema=always

# Optional: customize the name of the session table
spring.session.jdbc.table-name=SPRING_SESSION
